<div class="wrap">
  <div class="container">
    <div class="box">
      <div id="logo" class="col-xs-3"><img src="images/logo.png" class="img-responsive"/></div>
      <nav>
        <div class="desktop visible-md visible-lg">
          <ul>
            <li> <a href="index.php">Início</a></li>
            <li> <a href="todos-passeios.php">Próximos destinos</a></li>
            <li> <a href="#">Álbum</a></li>
            <li> <a href="#">Fale conosco</a></li>
            <li> <a href="#">Quem somos</a></li>
          </ul>
        </div>
        <div class="portables visible-xs visible-sm">
          <div class="header"><a href="#menu"> 
              <button type="button" class="btn btn-responsive btn-default">Opções</button></a></div>
        </div>
      </nav>
    </div>
  </div>
</div>