<!-- Smartphones -->
<div id='smartphone' class='visible-xs'> 
	
	<!-- Imagem Decorativa - Pontos turísticos -->
	<div class="row skyline">
		<div class="col-xs-offset-2 col-xs-8 text-center">
			<img src="images/skylinefinal.png" alt="" class="img-responsive">
		</div>
	</div>
	
	<!-- Logo e contato -->
	<div class="row logo-contato">
		
		<!-- logo -->
		<!-- <div class="pull-right col-xs-4">
			<img src="" alt="" class="img-responsive">
		</div>	 
	-->
	<!-- Contato -->
	<div class="contato">
		<ul class=" list-group text-center" >
			<li class=""><a href=""><i style='position: relative; top: 0.16em;' class="fa fa-phone fa-lg"></i>&nbsp;(21) 3867 - 9034</a></li>
			<li class=""><a href=""><i style='font-size:1.35em' class="fa fa-envelope fa-lg"></i>&nbsp;bragancatour@gmail.com</a></li>
			<a href="http://goo.gl/DGiUg2"><li class=""><i class="fa fa-facebook-square fa-lg"></i>&nbsp;Siga-nos no facebook!</li></a>
		</ul> 
	</div><!-- .contato -->	

</div><!-- row - Logo e  contato -->
</div><!-- end #smartphone -->

<!-- Tablet em diante -->
<div id="tablet-desktop" class='hidden-xs'>
	
	
	<!-- Logo e contato -->
	<div class="container">		
		<!-- Imagem Decorativa - Pontos turísticos -->
		<img src="images/skylinefinal.png" alt="" id='skyline'>
	</div>	
	
	
	<div class="wrapper">
		<div class="container" id="wrapper-child">
			<div id='contato-logo'>
				
				<!-- Contato -->
				<div class="contato">
					<ul class=" list-group" >
						<li class=""><a href=""><i style='position: relative; top: 0.16em;' class="fa fa-phone fa-lg"></i>&nbsp;(21) 3867 - 9034</a></li>
						<li class=""><a href=""><i style='font-size:1.35em' class="fa fa-envelope fa-lg"></i>&nbsp;bragancatour@gmail.com</a></li>
						<a href="http://goo.gl/DGiUg2"><li class=""><i class="fa fa-facebook-square fa-lg"></i>&nbsp;Siga-nos no facebook!</li></a>
					</ul> 
				</div>	 
				
				<!-- Logo -->
				<div class="logo">
					<img src="images/logo.png?version=1" alt="" class="img-responsive">
				</div>
			</div>
		</div>
		
	</div><!-- .wrapper -->
	
</div>	



</div>






