<meta charset="UTF-8">
<title>Início</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Início</title>


<!-- jQuery -->

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="js/jquery-1.11.2.min.js"></script>

<!-- Google font - Raleway -->


<!-- Font Awasome -->

	<link rel="stylesheet" href="plugins/font-awesome-4.3.0/css/font-awesome.min.css">

	
<!-- Mmenu -->

	<link type="text/css" href="css/jquery.mmenu.all.css" rel="stylesheet" />
	<script type="text/javascript" src="js/jquery.mmenu.min.all.js"></script>

<!-- Bootstrap --> 

	<link rel="stylesheet" href="plugins/bootstrap-3.3.2/dist/css/bootstrap.min.css">
	<script src="js/bootstrap.min.js"></script>

<!-- Waypoints -->

	<script src="plugins/waypoints/lib/jquery.waypoints.min.js"></script>
	

<!-- FlowType -->

	<script src="plugins/flowType/flowtype.js"></script>


<!-- CSS e Scripts customizados-->

	<link rel="stylesheet" href="css/custom.css">
	<script type="text/javascript" src="js/custom.js"></script>