
<div class="wrap">
  <div class="container">
    <div class="box">
      <div id="logo"><a href="index.php"><img src="images/logo.png?version=1" class="img-responsive"/></a></div>
      <nav>
        <div class="desktop visible-md visible-lg">
          <ul>
            <li> <a href="index.php">Início</a></li>
            <li> <a href="todos-passeios.php">Próximos Destinos</a></li>
            <li> <a href="http://goo.gl/0g6iZf">Álbum</a></li>
            <li> <a href="#proximos-encontros">Próximos Encontros</a></li>
            <li> <a href="#fale-conosco">Fale Conosco</a></li>
            <li> <a href="#quem-somos">Quem Somos</a></li>
            <li> <a href="http://goo.gl/l1w56f"> <i class="fa fa-facebook facebook fa-2x"></i></a></li>
          </ul>
        </div>
        <div class="portables visible-xs visible-sm">
          <div class="header"><a href="#menu"> 
              <button type="button" class="btn btn-responsive btn-default">opções</button></a><a href="http://goo.gl/l1w56f"> <i class="fa fa-facebook facebook fa-2x"></i></a></div>
        </div>
      </nav>
    </div>
  </div>
</div>