<ul>
  <div class='container' style='max-width:100%'>

    <li style="overflow: auto; padding:0 5%">
    
          <h2>Próximos encontros</h2>
          <h3><b>Vamos bater um papo?</b></h3>
          
          <p class="">Toda segunda 2º feira do mês nos encontramos para botar a conversa em dia, e conversar sobre os próximos passeios.</p>
          
          <p class="">
            Seguem <b>abaixo</b> a hora e o local dos próximos encontros. 
          </p>

          <?php $data_encontro = proximo_encontro(); ?>
          
          <p class=""> <b><?php echo $data_encontro;?></b> - 13:00 - Niterói -  Shopping BayMarket</p>
  
          <p class=""> <b><?php echo $data_encontro;?></b> - 18:00 - São Gonçalo -  Shopping BayMarket</p>
          
        
    </li>

  </div>
    
</ul>